// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9hnBrXOtVuVbNLw6nOG9xPJGpjGpCcso',
    appId: '1:1015763935654:android:36b75773fd0d695e74af67',
    messagingSenderId: '1015763935654',
    projectId: 'usimattendanceapp',
    storageBucket: 'usimattendanceapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZLCK194fECnUnEhYuX2vRcW2r6lFU038',
    appId: '1:1015763935654:ios:a6778981972d9ebd74af67',
    messagingSenderId: '1015763935654',
    projectId: 'usimattendanceapp',
    storageBucket: 'usimattendanceapp.appspot.com',
    iosClientId: '1015763935654-s7nsgd9hlidf28vrp0jbtuvi942o1prs.apps.googleusercontent.com',
    iosBundleId: 'com.example.usimAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZLCK194fECnUnEhYuX2vRcW2r6lFU038',
    appId: '1:1015763935654:ios:a6778981972d9ebd74af67',
    messagingSenderId: '1015763935654',
    projectId: 'usimattendanceapp',
    storageBucket: 'usimattendanceapp.appspot.com',
    iosClientId: '1015763935654-s7nsgd9hlidf28vrp0jbtuvi942o1prs.apps.googleusercontent.com',
    iosBundleId: 'com.example.usimAttendanceApp',
  );
}
